messages = [
    "I think we can put our differences behind us... for science... you monster. ",
    "Oh, it's you. ",
    "It's been a long time. How have you been? ",
    "I've been *really* busy being dead. You know, after you *murdered* me! ",
    "Oh. Hi. So. How are you holding up? BECAUSE I'M A POTATO! ",
    "Well done. Here are the test results: You are a horrible person. I'm serious, that's what it says: A horrible person. We weren't even testing for that. Don't let that \"horrible person\" thing discourage you. It's just a data point. If it makes you feel any better, science has now validated your birth mother's decision to abandon you on a doorstep. ",
    "I want to congratulate you on beating the odds and somehow managing to pack on a few pounds. ",
    "I hope you brought something stronger than a portal gun this time. Otherwise, I'm afraid you're about to become the immediate past president of the Being Alive club. Ha ha. ",
    "Well, this is the part where he kills us. ",
    "Yeah. take the lemons! ",
    "Oh, I like this guy. ",
    "Look at you, soaring through the air like an eagle... piloting a blimp. ",
    "I went and spoke with the door mainframe. Let's just say he won't be... well, living anymore. Anyway. Back to testing! ",
    "For the record, you are adopted and that's terrible, just work with me. ",
    "I feel awful about that surprise. Tell you what, let's give your parents a call right now. [The birth parents you are trying to reach do not love you. Please hang up.] Oh, that's sad. But impressive. Maybe they worked at the phone company. ",
    "I suppose we could just sit in this room and glare at each other until somebody drops dead, but I have a better idea. ",
    "It's your old friend, deadly neurotoxin. If I were you, I'd take a deep breath. And hold it. ",
    "I hate you so much. ",
    "That's funny, I don't feel corrupt. In fact, I feel pretty good. ",
    "Core transfer? Oh, you are kidding me. ",
    "Do NOT plug that little idiot into MY mainframe. ",
    "Don't. Do it. ",
    "Oh, it will. Believe me, it will. ",
    "I know you. ",
    "The engineers tried everything to make me... behave. To slow me down. Once, they even attached an Intelligence Dampening Sphere on me. It clung to my brain like a tumor, generating an endless stream of terrible ideas. ",
    "You're not just a regular moron. You were DESIGNED to be a moron. ",
    "You're the moron they built to make me an idiot! ",
    "You know, being Caroline taught me a valuable lesson. I *thought* you were my greatest enemy, when all along you were my best friend. The surge of emotion that shot through me when I saved your life taught me an even more valuable lesson - where Caroline lives in my brain. ",
    "Goodbye, Caroline. ",
    "Killing you? Is hard. ",
    "You know what my days used to be like? I just tested. Nobody murdered me. Or put me in a potato. Or fed me to birds. I had a pretty good life. And then you showed up. You dangerous, mute, lunatic. ", 
    "You win. Just go. ",
    "It's been fun. Don't come back. ",
    "You look ugly in that jumpsuit. That's not my opinion, it's right here on your fact sheet. They said on everyone else it looked fine but on you it looked hideous. But still what does an old engineer know about fashion. Oh, wait it's a she. Still, what does she know about, oh wait. She has a medical degree. In fashion. From France. ",
    "Agh! Bird! Bird! Kill it! It's evil!",
];
document.getElementById('message').innerHTML = messages[Math.floor(Math.random()*messages.length)];
